name: chaining jobs 1
on:
  workflow_dispatch:
    inputs:
      require-job-3:
        description: "If job 3 runs"
        required: true
        type: boolean

jobs:
  job-1:
    name: Job-1
    runs-on: ubuntu-latest
    steps:
      - name: echo job 1
        run: echo "This is job 1"
  job-2:
    name: job-2
    runs-on:
      - ubuntu-latest
    needs:
      - job-1
    steps:
      - name: run job 2
        run: echo "This is job 2"
  job-3:
    name: job-3
    runs-on:
      - ubuntu-latest
    if: github.event.inputs.require-job-3 == "true"
    needs:
    - job-1
    steps:
      - name: run job 3
        run: echo "This is job 3"
  job-4:
    name: run job 4
    runs-on: ubuntu-latest
    needs:
      - job-2
      - job-3
    steps:
      - name: run job steps
        run: echo "This is job 4"
        
